version: '3.8'

services:

  # ============================================================================
  # 1. Base de données PostgreSQL
  # ============================================================================
  ma-base-db:
    image: postgres:17
    container_name: Base_donnee_pfe_2026
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: g2ii_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ============================================================================
  # 2. Application Backend (Spring Boot)
  # ============================================================================
  backend-app:
    build:
      context: "D:\\Test pfe 2026\\g2ii" # 👈 Chemin absolu de ton projet Backend
      dockerfile: Dockerfile
    image: g2ii-backend-app:latest
    container_name: g2ii-app-container
    ports:
      - "8082:8082"
    depends_on:
      ma-base-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ma-base-db:5432/g2ii_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8082
    restart: on-failure

  # ============================================================================
  # 3. Application Frontend (Angular + Nginx)
  # ============================================================================
  frontend-app:
    build:
      context: "D:\\ProjetPFE2026Sagemcom\\ArchitecturePfe\\frontend\\apppfe" # 👈 Chemin absolu de ton projet Frontend
      dockerfile: Dockerfile
    image: g2ii-frontend-app:latest
    container_name: g2ii-frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend-app
    restart: always

  # ============================================================================
  # 4. Interface d'administration de la BDD
  # ============================================================================
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - ma-base-db

volumes:
  postgres_data: