server:
  port: 8070

spring:


  application:
    name: g2ii
  mail:
    host: smtp.gmail.com
    port: 587
    username: it.informatique.service@gmail.com   # Remplacez par votre vraie adresse
    password: ztcf dhkn kjee hfve # ⚠️ Lisez la note importante ci-dessous !
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
logging:
  level:
    root: INFO
    com.sagem.g2ii: DEBUG
  file:
    name: /app/logs/g2ii.log

# JWT Configuration
app:
  jwt:
    secret: mySecretKeyForJWTTokenGenerationThatMustBeAtLeast256Bits
    expiration: 86400000  # 24 heures en millisecondes

